Checks for presence of .vimrc, too

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,6 +5,12 @@ then
     echo "if you want to install you must delete ~/.profane"
     exit 1
 fi
+if [ -a $HOME/.vimrc ];
+then
+    echo "~/.vimrc exists, aborting"
+    echo "if you want to install you must delete ~/.vimrc"
+    exit 1
+fi
 ln -s $PWD/.vimrc $HOME/.vimrc
 ln -s $PWD/.profane $HOME/.profane
 exit 0
